/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controler.ketnoi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.*;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quan_li_phong_gym.Nhan_vien;

/**
 *
 * @author Admin
 */
public class Nhanvien extends javax.swing.JFrame {
    ArrayList<Nhan_vien> listnv = new ArrayList<Nhan_vien>();
    int current =0;
    /**
     * Creates new form Nhanvien
     */
    public Nhanvien() {
        initComponents();
         setLocationRelativeTo(null);
        LoadDataToArray();
        LoadDataArrayListtoTable();
    }
     ketnoi kn =new ketnoi();
    Connection conn ;
    PreparedStatement pst ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Display(int i){
    Nhan_vien nv= listnv.get(i);
    txtTennv.setText(nv.getTen());
    txtCccdnv.setText(nv.getCccd());
    txtSdtnv.setText(nv.getSdt());
        if (nv.getGioitinh().equals("Nam")||nv.getGioitinh().equals("nam")) {
            cbbGioitinhnv.setSelectedIndex(0);
        } else {            cbbGioitinhnv.setSelectedIndex(1);

        }
        txtManv.setText(nv.getManv());
    }
    public void LoadDataToArray(){
    conn = kn.getConnection();

        try {
           Statement st = conn.createStatement();
             String sql = "select * from Nhanvien";
            ResultSet rs =st.executeQuery(sql);
            listnv.clear();
            while (rs.next()) {       
                String ten =rs.getString(1);
                String cccd =rs.getString(2);
                String sdt = rs.getString(3);
                String gioitinh =rs.getString(4);
                String manv =rs.getString(5);
                Nhan_vien nv =new Nhan_vien(manv, ten, cccd, sdt, gioitinh);
                listnv.add(nv);
        } 
        }catch (SQLException ex) {
            Logger.getLogger(Nhanvien.class.getName()).log(Level.SEVERE, null, ex);
    
    }   
        }
      public void LoadDataArrayListtoTable(){
        DefaultTableModel model = (DefaultTableModel) tblnv.getModel();
        model.setRowCount(0);
        for (Nhan_vien h: listnv) {
            model.addRow(new Object[]{h.getTen(),h.getCccd(),h.getSdt(),h.getGioitinh(),h.getManv()});
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTennv = new javax.swing.JTextField();
        txtCccdnv = new javax.swing.JTextField();
        txtSdtnv = new javax.swing.JTextField();
        cbbGioitinhnv = new javax.swing.JComboBox<>();
        label1 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        txttim = new javax.swing.JTextField();
        btnTimnv = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblnv = new javax.swing.JTable();
        btnnhaplainv = new javax.swing.JButton();
        btnThemnv = new javax.swing.JButton();
        btnXoanv = new javax.swing.JButton();
        btnSuanv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NHÂN VIÊN");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Sdt");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cccd");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Giới tính");

        txtTennv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTennvActionPerformed(evt);
            }
        });

        txtCccdnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCccdnvActionPerformed(evt);
            }
        });

        cbbGioitinhnv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ ", "Khác", " " }));
        cbbGioitinhnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbGioitinhnvActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label1.setText("Mã NV");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbGioitinhnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSdtnv, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(txtManv)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCccdnv, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtTennv)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCccdnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSdtnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbGioitinhnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        btnTimnv.setText("Tìm");

        tblnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên", "Cccd", "Sdt", "Giới tính", "Mã nv"
            }
        ));
        tblnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnvMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblnv);

        btnnhaplainv.setText("Nhập lại");
        btnnhaplainv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhaplainvActionPerformed(evt);
            }
        });

        btnThemnv.setText("Thêm");
        btnThemnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemnvActionPerformed(evt);
            }
        });

        btnXoanv.setText("Xóa");
        btnXoanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoanvActionPerformed(evt);
            }
        });

        btnSuanv.setText("Sửa");
        btnSuanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuanvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemnv)
                        .addGap(9, 9, 9)
                        .addComponent(btnXoanv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuanv)
                        .addGap(3, 3, 3)
                        .addComponent(btnnhaplainv))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimnv))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnnhaplainv)
                            .addComponent(btnThemnv)
                            .addComponent(btnXoanv)
                            .addComponent(btnSuanv)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTimnv)
                            .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTennvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTennvActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTennvActionPerformed

    private void txtCccdnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCccdnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCccdnvActionPerformed

    private void cbbGioitinhnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbGioitinhnvActionPerformed
        
    }//GEN-LAST:event_cbbGioitinhnvActionPerformed
public boolean checkValidateForm(){
        if (txtTennv.getText().isEmpty()||txtCccdnv.getText().isEmpty()
                ||txtManv.getText().isEmpty()||txtSdtnv.getText().isEmpty()) {
            return false;
        } else {
            return true ;
        }
}
    private void btnnhaplainvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhaplainvActionPerformed
        // TODO add your handling code here:
        txtTennv.setText("");
            
            txtCccdnv.setText("");
            txtSdtnv.setText("");
            cbbGioitinhnv.setSelectedItem(1);
            txtManv.setText("");
            txttim.setText("");
    }//GEN-LAST:event_btnnhaplainvActionPerformed

    private void tblnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnvMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblnv.getModel();

        current=tblnv.getSelectedRow();
        Display(current);
    }//GEN-LAST:event_tblnvMouseClicked

    private void btnThemnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemnvActionPerformed
        // TODO add your handling code here:
          if (!checkValidateForm()) {
             JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin ");
        } else {
        
        String tennv = txtTennv.getText();
        String cccd =txtCccdnv.getText();
        String gioitinh =cbbGioitinhnv.getSelectedItem().toString();
        String sdt =txtSdtnv.getText();
        String manv =txtManv.getText();
        try {conn =kn.getConnection();
            pst = conn.prepareStatement("insert into dbo.Nhanvien values(?,?,?,?,?)");
             pst.setString(1, tennv);
            
            pst.setString(2, cccd);
            pst.setString(3, sdt);
            pst.setString(4, gioitinh);
            pst.setString(5, manv);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Đã thêm Nhân viên");
            txtTennv.setText("");
            
            txtCccdnv.setText("");
            txtSdtnv.setText("");
            cbbGioitinhnv.setSelectedItem(1);
            txtManv.setText("");
            txtTennv.requestFocus();
        } catch (Exception e) {
        }
        }
         LoadDataToArray();
           LoadDataArrayListtoTable();
    }//GEN-LAST:event_btnThemnvActionPerformed

    private void btnXoanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoanvActionPerformed
        // TODO add your handling code here:
        if (txtManv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên");
            txtManv.requestFocus();
        }else{
        try { 
                String connectionURL = "jdbc:sqlserver://localhost:1433;databaseName=doannhom11;user=sa;password=123456;encrypt=false";
            conn = DriverManager.getConnection(connectionURL);
           String sql = "delete from dbo.Nhanvien where Manv = ?";
            pst = conn.prepareStatement(sql);
           pst.setString(1, txtManv.getText());
           txtTennv.setText("");
            
            txtCccdnv.setText("");
            txtSdtnv.setText("");
            cbbGioitinhnv.setSelectedItem(1);
            txtManv.setText("");
           pst.executeUpdate();
           JOptionPane.showMessageDialog(this, "Đã xóa thành công ");
           //conn.close();
           
            } 
            catch (HeadlessException | SQLException e) {
                System.out.println(e);
            }
           LoadDataToArray();
           LoadDataArrayListtoTable();
        }
    }//GEN-LAST:event_btnXoanvActionPerformed

    private void btnSuanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuanvActionPerformed
        // TODO add your handling code here:
        if (txtManv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nv");
            txtManv.requestFocus();
         }else{
                String connectionURL = "jdbc:sqlserver://localhost:1433;databaseName=doannhom11;user=sa;password=123456;encrypt=false";
        try { //Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(connectionURL);
            String sql1= "update Nhanvien set Ten=?,Cccd=?,Sdt=?,Gioitinh=? Where Manv=?";
            pst =conn.prepareStatement(sql1);
              String tennv=txtTennv.getText();
        
        String CCCD= txtCccdnv.getText();
        String Gioitinh =cbbGioitinhnv.getSelectedItem().toString();
        String sdt = txtSdtnv.getText();
        String manv =txtManv.getText();
        pst.setString(1, tennv);
          
            pst.setString(2, CCCD);
            pst.setString(3, sdt);
            pst.setString(4, Gioitinh);
            pst.setString(5, manv);
            pst.executeUpdate();
            txtTennv.setText("");
            
            txtCccdnv.setText("");
            txtSdtnv.setText("");
            cbbGioitinhnv.setSelectedItem(1);
            txtManv.setText("");
            
            conn.close();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        } catch (SQLException ex) {
            Logger.getLogger(Hlv.class.getName()).log(Level.SEVERE, null, ex);
        } 
      LoadDataToArray();
    LoadDataArrayListtoTable();}
    }//GEN-LAST:event_btnSuanvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuanv;
    private javax.swing.JButton btnThemnv;
    private javax.swing.JButton btnTimnv;
    private javax.swing.JButton btnXoanv;
    private javax.swing.JButton btnnhaplainv;
    private javax.swing.JComboBox<String> cbbGioitinhnv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JTable tblnv;
    private javax.swing.JTextField txtCccdnv;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtSdtnv;
    private javax.swing.JTextField txtTennv;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
