/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import quan_li_phong_gym.The_hoi_vien;
import java.util.List;
import Controler.ketnoi;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author macos
 */
public class Thehoivien extends javax.swing.JFrame {

ArrayList<The_hoi_vien> listthv = new ArrayList<The_hoi_vien>();
int current=0;

    DateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
    /**
     * Creates new form doannhom11
     */
    public Thehoivien() {
        initComponents();
         setLocationRelativeTo(null);
      LoadDataToArray();
      LoadDataArrayListtoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.set
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ketnoi kn =new ketnoi();
    Connection conn ;
    PreparedStatement pst;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblthehv = new javax.swing.JTable();
        txtmathehv = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txtngayhethan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btndangky = new javax.swing.JButton();
        btnhaplai = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txttim = new javax.swing.JTextField();
        cbbhangthe = new javax.swing.JComboBox<>();
        cbbgoitap = new javax.swing.JComboBox<>();
        cbbgiatien = new javax.swing.JComboBox<>();
        cbbmakhoatap = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblthehv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thẻ hv ", "Tên ", "Hạng thẻ ", "Mã khoá tập ", "Gói tập ", "Gía tiền ", "Ngày hết hạn"
            }
        ));
        tblthehv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblthehvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblthehv);

        txtngayhethan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngayhethanActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã thẻ hv ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Hạng thẻ ");

        jLabel4.setText("Mã khoá tập ");

        jLabel5.setText("Gói tập ");

        jLabel6.setText("Giá tiền ");

        jLabel7.setText("Ngày hết hạn ");

        btndangky.setText("Đăng ký ");
        btndangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangkyActionPerformed(evt);
            }
        });

        btnhaplai.setText("Nhập lại");
        btnhaplai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhaplaiActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xoá");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setBackground(new java.awt.Color(153, 51, 255));
        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ĐĂNG KÝ THẺ THÀNH VIÊN ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Tìm kiếm ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbbhangthe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silver", "Gold", "Platinum", " " }));

        cbbgoitap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 tháng", "1 năm", "2 năm vip" }));

        cbbgiatien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2.000.000", "3.000.000", "7.000.000" }));

        cbbmakhoatap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001", "002", "003" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cbbhangthe, 0, 150, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbbgiatien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbbgoitap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(cbbmakhoatap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(txtngayhethan, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtmathehv, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(49, 49, 49)
                                                .addComponent(jButton1)
                                                .addGap(39, 39, 39)
                                                .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(btnsua)
                                                .addGap(27, 27, 27)
                                                .addComponent(btnhaplai)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btndangky)
                                .addGap(18, 18, 18)
                                .addComponent(btnxoa)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmathehv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cbbhangthe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cbbmakhoatap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cbbgoitap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cbbgiatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtngayhethan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndangky)
                            .addComponent(btnhaplai)
                            .addComponent(btnxoa)
                            .addComponent(btnsua))
                        .addGap(213, 213, 213))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(535, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void Display(int i){
   The_hoi_vien thv =listthv.get(i);
txtmathehv.setText(thv.getMathehv());
txtngayhethan.setText(thv.getNgayhethanString());
txtten.setText(thv.getTen());
     if (thv.getHangthe().equals("Silver")) {
         cbbgoitap.setSelectedIndex(0);
        cbbhangthe.setSelectedIndex(0);
        cbbgiatien.setSelectedIndex(0);
        cbbmakhoatap.setSelectedIndex(0);
   
     } else if (thv.getHangthe().equals("Gold")) {
             cbbgoitap.setSelectedIndex(1);
        cbbhangthe.setSelectedIndex(1);
        cbbgiatien.setSelectedIndex(1);
        cbbmakhoatap.setSelectedIndex(1);
         } else {
             cbbgoitap.setSelectedIndex(2);
        cbbhangthe.setSelectedIndex(2);
        cbbgiatien.setSelectedIndex(2);
        cbbmakhoatap.setSelectedIndex(2);
         }
     
        
    }
    
public void LoadDataToArray(){
    conn = kn.getConnection();
// ket noi list hoi vien
        try {
           
             // ket noi  list the hoi vien
              Statement st1 = conn.createStatement();
             String sql1 = "select * from Thehoivien";
            ResultSet rs1 =st1.executeQuery(sql1);
            listthv.clear();
            while (rs1.next()) {       
               
                The_hoi_vien thv=new The_hoi_vien(rs1.getString(1),rs1.getString(2) , rs1.getString(3), rs1.getString(4), rs1.getString(5), rs1.getString(6), rs1.getDate(7));
                listthv.add(thv);
            }    
             
        }catch (SQLException ex) {
            Logger.getLogger(Nhanvien.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
    
    }   
        }
public void LoadDataArrayListtoTable(){
         
         DefaultTableModel model1 = (DefaultTableModel) tblthehv.getModel();
         model1.setRowCount(0);
         for (The_hoi_vien thv: listthv) {
            model1.addRow(new Object[]{thv.getMathehv(),thv.getTen(),thv.getHangthe(),thv.getMakhoatap(),thv.getGoitap(),thv.getGiatien(),thv.getNgayhethan()});
        }
         
    }
public boolean checkValidateForm(){
        if (txtten.getText().isEmpty()||txtmathehv.getText().isEmpty()
               ||txtngayhethan.getText().isEmpty()) {
            return false;
        } else {
            return true ;
        }
}
    private void btndangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangkyActionPerformed
        if (!checkValidateForm()) {
             JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin ");
        } else {
        
        
        try {
            conn =kn.getConnection();
           ;
            //Dang ki the hoi vien
         
            pst =conn.prepareStatement("insert into dbo.Thehoivien values(?,?,?,?,?,?,?)");
            pst.setString(1, txtmathehv.getText());
            pst.setString(2, txtten.getText());
            pst.setString(3, cbbhangthe.getSelectedItem().toString());
            pst.setString(4, cbbmakhoatap.getSelectedItem().toString());
            pst.setString(5, cbbgoitap.getSelectedItem().toString());
            pst.setString(6, cbbgiatien.getSelectedItem().toString());
            
            try {
                pst.setDate(7, new Date(sdf.parse(txtngayhethan.getText()).getTime()));
            } catch (ParseException ex) {
                Logger.getLogger(Thehoivien.class.getName()).log(Level.SEVERE, null, ex);
            }
            pst.executeUpdate();
             txtmathehv.setText("");
             txtten.setText("");
             txtngayhethan.setText("");

            txtmathehv.requestFocus();
            
            JOptionPane.showMessageDialog(this, "Đã thêm hội viên");
        } catch (HeadlessException | SQLException  e) {
            e.printStackTrace();
        }
         LoadDataToArray();
      LoadDataArrayListtoTable();
        } 
    }//GEN-LAST:event_btndangkyActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (txtmathehv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã thẻ hv");
            txtmathehv.requestFocus();
         }else{
                String connectionURL = "jdbc:sqlserver://localhost:1433;databaseName=doannhom11;user=sa;password=123456;encrypt=false";
        try { //Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(connectionURL);
            String sql1= "update Thehoivien set Ten=?,Hangthe=?,Makhoatap=?,Goitap=?,Giatien=?,Ngayhethan=? Where Mathehv=?";
            pst =conn.prepareStatement(sql1);
              
        pst.setString(1, txtmathehv.getText());
          
            pst.setString(2, txtten.getText());
            pst.setString(3, cbbhangthe.getSelectedItem().toString());
            pst.setString(4, cbbmakhoatap.getSelectedItem().toString());
            pst.setString(5,cbbgoitap.getSelectedItem().toString());
            pst.setString(6, cbbgiatien.getSelectedItem().toString());
             pst.setDate(7, new Date(sdf.parse(txtngayhethan.getText()).getTime()));
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        } catch (SQLException ex) {
            Logger.getLogger(Hlv.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (ParseException ex) { 
                Logger.getLogger(Thehoivien.class.getName()).log(Level.SEVERE, null, ex);
            }
      LoadDataToArray();
    LoadDataArrayListtoTable();}
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnhaplaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhaplaiActionPerformed
             txtmathehv.setText("");
             txtten.setText("");
             txtngayhethan.setText("");  
              cbbgoitap.setSelectedIndex(0);
        cbbhangthe.setSelectedIndex(0);
        cbbgiatien.setSelectedIndex(0);
        cbbmakhoatap.setSelectedIndex(0);
        txttim.setText("");
      // TODO add your handling code here:
    }//GEN-LAST:event_btnhaplaiActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO addxoathongtin () your handling code here:
       if (txtmathehv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã hội viên");
            txtmathehv.requestFocus();
        }else{
        try { 
                String connectionURL = "jdbc:sqlserver://localhost:1433;databaseName=doannhom11;user=sa;password=123456;encrypt=false";
            conn = DriverManager.getConnection(connectionURL);
           String sql = "delete from dbo.Thehoivien where Mathehv = ?";
            pst = conn.prepareStatement(sql);
           pst.setString(1, txtmathehv.getText());
           pst.executeUpdate();
           
          
           JOptionPane.showMessageDialog(this, "Đã xóa thành công ");
           //conn.close();
           
            } 
            catch (HeadlessException | SQLException e) {
                System.out.println(e);
            }
           LoadDataToArray();
           LoadDataArrayListtoTable();
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtngayhethanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngayhethanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngayhethanActionPerformed

    private void tblthehvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblthehvMouseClicked
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) tblthehv.getModel();

        current=tblthehv.getSelectedRow();
        Display(current);
                             
    }//GEN-LAST:event_tblthehvMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thehoivien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thehoivien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thehoivien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thehoivien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thehoivien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangky;
    private javax.swing.JButton btnhaplai;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbbgiatien;
    private javax.swing.JComboBox<String> cbbgoitap;
    private javax.swing.JComboBox<String> cbbhangthe;
    private javax.swing.JComboBox<String> cbbmakhoatap;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblthehv;
    private javax.swing.JTextField txtmathehv;
    private javax.swing.JTextField txtngayhethan;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txttim;
    // End of variables declaration//GEN-END:variables
}
